---
title: "足球数据分析"
author: "韩子航 2019202424"
date: "2022/3/28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(RSQLite)
library(reldist)
```

```{r}
con <- dbConnect(SQLite(), dbname="C:/Users/hp/Desktop/database.sqlite")

dbListTables(con)
```

```{r}
League <- tbl_df(dbGetQuery(con,"SELECT * FROM League"))
Match <- tbl_df(dbGetQuery(con,"SELECT * FROM Match"))
Player <- tbl_df(dbGetQuery(con,"SELECT * FROM Player"))
Player_Attributes <- tbl_df(dbGetQuery(con,"SELECT * FROM Player_Attributes"))
Team_Attributes <- tbl_df(dbGetQuery(con,"SELECT * FROM Team_Attributes"))
Team <- tbl_df(dbGetQuery(con,"SELECT * FROM Team"))
Country <- tbl_df(dbGetQuery(con,"SELECT * FROM Country"))
```

```{r}
myCor <- cor(Player_Attributes[c(5,6,10:42)])
library(corrplot)
corrplot(myCor, type = "upper")
```
球员贡献的相关性分析
```{r}
library(qtlcharts)

iplotCorr(Player_Attributes[,c(5,6,10:42)], reorder=TRUE)
```

```{r}
hist(Player_Attributes$overall_rating)
hist(Player_Attributes$potential)
```
主客场胜率分析
```{r}
library(lubridate)
library(dplyr)
library(RSQLite)
library(ggplot2)
library(reshape2)
library(ggrepel)
sqlite_drv <- dbDriver("SQLite")
sql_db <- dbConnect(sqlite_drv,"C:/Users/hp/Desktop/database.sqlite")
match_df <- dbGetQuery(sql_db,"select * from Match")
team_df <- dbGetQuery(sql_db,"select * from Team")
country_df <- dbGetQuery(sql_db,"select * from Country")
league_df <- dbGetQuery(sql_db,"select * from League")
```

```{r}
match_df_imp <- match_df[,1:11]
away_team_matches <- merge(team_df,match_df_imp,by.x="team_api_id",by.y="away_team_api_id")
home_team_matches <- merge(team_df,match_df_imp,by.x="team_api_id",by.y="home_team_api_id")
home_team_matches <- subset(home_team_matches,select=-c(id.x,id.y))
away_team_matches <- subset(away_team_matches,select=-c(id.x,id.y))
colnames(home_team_matches)[11:13] <- c("opponent_team_id","goals_scored","goals_conceded")
colnames(away_team_matches)[11:13] <- c("opponent_team_id","goals_conceded","goals_scored")
home_team_matches <- cbind(home_team_matches,side="home")
away_team_matches <- cbind(away_team_matches,side="away")
all_matches <- rbind(home_team_matches,away_team_matches)

all_matches <- all_matches %>% mutate(result=ifelse(goals_scored > goals_conceded,"win",ifelse(goals_scored < goals_conceded,"loss","draw")))
team_stats <- all_matches %>% group_by(team_long_name,league_id) %>% summarise(matches=n(),h_matches=length(result[side=="home"]),a_matches=length(result[side=="away"]),
                  tot_scored=sum(goals_scored),home_scored=sum(goals_scored[side=="home"]),away_scored=sum(goals_scored[side=="away"]),
                  tot_conceded = sum(goals_conceded),home_conceded=sum(goals_conceded[side=="home"]),away_conceded = sum(goals_conceded[side=="away"]),
                  wins=length(result[result=="win"]),losses=length(result[result=="loss"]),draws=length(result[result=="draw"]),
                  h_wins=length(result[result=="win" & side=="home"]), a_wins=length(result[result=="win" & side=="away"]),
                  h_loss=length(result[result=="loss" & side=="home"]), a_loss=length(result[result=="loss" & side=="away"]),
                  mean_goals=mean(goals_scored),var_goals=var(goals_scored), win_pct=wins/matches,loss_pct=losses/matches,
                  hwin_pct=h_wins/h_matches, awin_pct=a_wins/a_matches)

team_stats <- inner_join(ungroup(team_stats),league_df,by=c("league_id"="id")) %>% select(-one_of("country_id","league_id")) %>% rename(league_name=name)
```

```{r}
league_stats <- team_stats %>% group_by(league_name) %>% summarise(num_teams=n_distinct(team_long_name),num_matches=sum(matches)/2,
                                                                   num_draws=sum(draws)/2) %>% arrange(desc(num_matches))
```

```{r}
print(league_stats %>% select(-one_of("num_draws")))
```


```{r}
plot_wpct_freq <- 
  ggplot(team_stats,aes(win_pct*100))+geom_area(stat="bin",bins=10,fill="light blue")+xlab("Winning percentage")


l1=ggplot(team_stats,aes(mean_goals))+geom_area(stat="bin",bins=10,fill="light blue")+xlab("home Winning percentage")

l2=ggplot(team_stats,aes(awin_pct*100))+geom_area(stat="bin",bins=10,fill="light blue")+xlab("away Winning percentage")

l1
l2
```


```{r}
library(ggpp)
team_win=team_stats[,c(20,22,23)]
colnames(team_win)=c("all","home","away")
team_win<-melt(
       team_win,                       #待转换的数据集名称
         #要保留的主字段
       variable.name="field",         #转换后的分类字段名称（维度）
       value.name="win_rate"             #转换后的度量值名称
       )
ggplot(team_win, aes(x=win_rate, fill=field)) +
              geom_density(alpha=.5,col="white")+geom_vline(xintercept = 0.5,linetype = "dashed")   # 线的形状为“虚线”
```
胜率与排行分析
```{r}
spain_team_stats=team_stats[team_stats$league_name=="Spain LIGA BBVA",]
top_win_teams = spain_team_stats %>% arrange(desc(win_pct)) %>% head(20) 
plot_top_teams =
ggplot(top_win_teams,aes(x=reorder(team_long_name,-win_pct),y=win_pct,fill=league_name))+
  geom_bar(stat = 'identity')+theme(axis.text.x=element_text(angle=90))+coord_cartesian(ylim = c(0.2, 0.8))+
  xlab("Team name")+ylab("Win Rate")
plot_top_teams
```


```{r}
top_win_teams = team_stats %>% arrange(desc(win_pct)) %>% head(20) 
plot_top_teams =
ggplot(top_win_teams,aes(x=reorder(team_long_name,-win_pct),y=win_pct,fill=league_name))+
  geom_bar(stat = 'identity')+theme(axis.text.x=element_text(angle=90))+coord_cartesian(ylim = c(0.5, 0.8))+
  xlab("Team name")+ylab("Win Rate")
plot_top_teams
```

```{r}
top_win_teams = team_stats %>% arrange(desc(mean_goals)) %>% head(20) 
plot_top_teams =
ggplot(top_win_teams,aes(x=reorder(team_long_name,-mean_goals),y=mean_goals,fill=league_name))+
  geom_bar(stat = 'identity')+theme(axis.text.x=element_text(angle=90))+coord_cartesian(ylim = c(1, 3))+
  xlab("Team name")+ylab("Mean Goals")
plot_top_teams
```

```{r}
top_win_teams = team_stats %>% arrange(desc(mean_goals)) %>% head(10) 
plot_team_consistency <- 
ggplot(top_win_teams,aes(x=mean_goals,y=win_pct))+geom_point()+
  geom_text(aes(label=team_long_name,vjust=1),size=4)+xlab("Average number of goals scored")+
ylab("Win Rate")+scale_x_continuous(breaks=seq(1,3.5,by=0.1))+scale_y_continuous(breaks=seq(1,10,by=0.1))
plot_team_consistency
```

```{r}
team_season_stats <- all_matches %>% group_by(team_long_name,league_id,season) %>% summarise(matches=n(),h_matches=length(result[side=="home"]),a_matches=length(result[side=="away"]),
                                                                                             tot_scored=sum(goals_scored),tot_conceded = sum(goals_conceded),
                                                                                             wins=length(result[result=="win"]),losses=length(result[result=="loss"]),draws=length(result[result=="draw"]),
                                                                                             mean_goals=mean(goals_scored),var_goals=var(goals_scored), win_pct=wins/matches,loss_pct=losses/matches
                                                                                             )
top_10_teams <- team_stats %>% arrange(desc(win_pct)) %>% head(5) 
top_team_season_stats <- team_season_stats %>% filter(team_long_name %in% top_10_teams$team_long_name)
plot_top_team_wpct <-ggplot(top_team_season_stats,aes(x=season,y=win_pct*100,colour=team_long_name,group=team_long_name))+geom_line(size=1.5)+
                        geom_label_repel(data=subset(top_team_season_stats,season=="2015/2016" | season == "2008/2009"),aes(label=paste(team_long_name, format(win_pct*100 ,digits=3))),segment.color = NA)+
                        scale_color_discrete(guide="none")+ylab("Win Rate")
plot_top_team_wpct
```

```{r}
Player_Attributes$Pace=Player_Attributes$acceleration*0.45+Player_Attributes$sprint_speed*0.55

Player_Attributes$Shooting=Player_Attributes$finishing*0.45+Player_Attributes$long_shots*0.2+Player_Attributes$penalties*0.05+Player_Attributes$shot_power*0.2+Player_Attributes$volleys*0.1
#不存在Att.Pos故将其份额赋予volleys

Player_Attributes$Passing=Player_Attributes$vision*0.2+Player_Attributes$crossing*0.2+Player_Attributes$curve*0.05+Player_Attributes$free_kick_accuracy*0.05+Player_Attributes$long_passing*0.15+Player_Attributes$short_passing*0.35

Player_Attributes$Dribbling=Player_Attributes$dribbling*0.5+Player_Attributes$agility*0.1+Player_Attributes$balance*0.05+Player_Attributes$reactions*0.05+Player_Attributes$ball_control*0.3

Player_Attributes$Defending=Player_Attributes$interceptions*0.2+Player_Attributes$heading_accuracy*0.1+Player_Attributes$marking*0.3+Player_Attributes$sliding_tackle*0.1+Player_Attributes$standing_tackle*0.3

Player_Attributes$Physical=Player_Attributes$aggression*0.2+Player_Attributes$jumping*0.05+Player_Attributes$stamina*0.25+Player_Attributes$strength*0.5
```

```{r}
write.csv(Player_Attributes,"C:/Users/hp/Desktop/Player_Attributes.csv")
```

